### ISSUE TITLE
How to solve the dependency issue

### ISSUE THREAD

**Issue by tigerjiang** [supervons/ExploreRN#18]
iangzehu@Tigers-Book ExploreRN % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ExploreRN@0.0.1
npm ERR! Found: react-native@0.66.1
npm ERR! node_modules/react-native
npm ERR!   react-native@"^0.66.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.58.0" from react-native-echarts-liquidfill@1.0.1
npm ERR! node_modules/react-native-echarts-liquidfill
npm ERR!   react-native-echarts-liquidfill@"^1.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jiangzehu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jiangzehu/.npm/_logs/2021-10-28T04_02_51_551Z-debug.log

**Comment by supervons** [comment]
I will continue to follow up this bugs when other people face it.
